feat: add plural rule into compiled catalogs
lingui/js-lingui pull request #1311
Opened 2022-12-12 12:35 UTC by thekip

## Description
This PR adds support for emiting plural rule (what `make-plural/plurals` is currently used for) into compiled catalog. 
This allows users to avoid installing and importing `make-plural/plurals` in theirs code and use only catalogs instead. 

Following official [documentation](https://lingui.js.org/guides/dynamic-loading-catalogs.html#final-i18n-loader-helper) preferred way to setup is: 

```typescript
import { i18n } from '@lingui/core';
import { en, cs } from 'make-plural/plurals'

i18n.loadLocaleData({
  en: { plurals: en },
  cs: { plurals: cs },
})

export async function dynamicActivate(locale: string) {
  const { messages } = await import(`./locales/${locale}/messages`)
  i18n.load(locale, messages)
  i18n.activate(locale)
}
```

Which is in fact will always load plurals functions for locales which are currently not used on the page. 

After this change, user would be able to write like this: 
```typescript
import { i18n } from "@lingui/core"

export async function dynamicActivate(locale: string) {
  const { messages, plurals } = await import(`./locales/${locale}/messages`)
  i18n.load(locale, messages)

  i18n.loadLocaleData(locale, {
    plurals
  })

  i18n.activate(locale)
}
```

## Notes

1. I'm taking the plural function from `make-plural/plurals` and serialize it into the string. Then when compiling catalogs into AST I convert stringified function into AST and inject to the output file. 

Compilation now produces: 

```typescript
module.exports = {
    messages: {"Hello": "Alohà"},
    plurals: (n, ord) => {
        return n == 1 ? "one" : "other"
    }
}
```

2. I deleted `pure` option from `createCompiledCatalog` because it's not used anywhere in the project. This API considered internal, so we should be on the safe side. 
It's probably was created for `remote-loader` but code has been changed since then and now this option is obsolete.

2022-12-12 12:51 UTC, thekip commented on packages/cli/api.d.ts
> +export * from "./src/api"
I added this to help IDE and Typescript to see typings from sources. Otherwise everethyng imported from /api was `any`

2023-01-10 13:32 UTC, thekip commented
This one would have conflicts after merging https://github.com/lingui/js-lingui/pull/1328

2023-01-11 16:55 UTC, thekip commented
Done

2023-01-13 09:12 UTC, Martin005 requested changes
These changes look really great!

I have added a few comments and it would be great to include this in the documentation, could you please add it there?

2023-01-17 11:37 UTC, thekip commented
I have to postpone it for a while, until we solve this https://github.com/lingui/js-lingui/issues/1339 

After this change catalog became non-serializable to json (because of the function inside) and my example nextjs integration would not work.

2023-02-20 12:34 UTC, thekip commented
I think this solution is better https://github.com/lingui/js-lingui/issues/1446

2023-02-20 12:34 UTC, closed without merging