refactor(macro): make code strongly typed
lingui/js-lingui pull request #1321
Opened 2023-01-04 11:20 UTC by thekip

No logic changes. Added types wherever possible and fix issues. Also added few more tests for "black zones".

2023-01-04 11:20 UTC, thekip commented
@andrii-bodnar FYI

2023-01-10 15:07 UTC, Martin005 requested changes
Thank you for your pull request!

I have made some suggestions and [commented one question](https://github.com/lingui/js-lingui/pull/1321#discussion_r1065853488).

From the 3 empty lines and no spaces around value names in `import`'s, I believe you are not running Prettier. Please set it up and run it on this PR.

As we have merged your PR #1329 into main, please merge main into your branch as that PR made some changes to the `packages/macro/src/index.ts` file.

2023-01-10 15:27 UTC, thekip commented on packages/macro/src/macroJs.ts
>    replacePathWithMessage = (
I carefully checked all paths and write comprehensive TS typings and this was not used. That is a part of some outdated code.  All tests related comment and ID still passing.

2023-01-10 15:32 UTC, thekip commented on packages/macro/src/macroJsx.ts
> +      .filter(() => Boolean))
Seems this is not covered by tests

2023-01-10 15:37 UTC, thekip commented
messed up things with rebase, looking why commits from main is showed as my

2023-01-10 15:51 UTC, thekip commented
Done

2023-01-10 19:07 UTC, Martin005 approved these changes

2023-01-11 08:36 UTC, andrii-bodnar commented
@thekip @Martin005 is this PR ready to merge?

2023-01-11 08:53 UTC, thekip commented
Nothing to add from my side

2023-01-11 09:38 UTC, merged