refactor(core) bump messageformat parser. Add TS types
lingui/js-lingui pull request #1328
Opened 2023-01-09 09:50 UTC by thekip

Bumped version of the upstream messageformat parser to 5.0, updated what's broke and add TS typings wherever possible in touched files. 

Resolves https://github.com/lingui/js-lingui/issues/1278

Should be no changes in logic, but public types slightly changed. They became more accurate, so it's better to bump a version just in case. 

How current config of semver works, should i name a PR with special prefix or commit message or it's doing manually?

2023-01-09 09:58 UTC, andrii-bodnar commented
@thekip thanks for the contribution!

Probably, I'll ask @Martin005 to review this PR.

> How current config of semver works, should i name a PR with special prefix or commit message or it's doing manually?

It expects that the PR title will be specified according to the following format:

https://github.com/amannn/action-semantic-pull-request#validation

2023-01-10 11:12 UTC, Martin005 commented
@thekip You made changes only to the `@lingui/core` package.
Could you please also update the `@lingui/cli` and `@lingui/remote-loader`? They currently also use the `messageformat-parser` package.

Also, updating the package may also fix issues #1033 and #1075 🙂

2023-01-10 13:26 UTC, thekip commented
My bad, didn't check this. 

This commit is bigger, few things about what changed: 

1. I've found a code duplication (3 times) where tokens from `message-parser` were converted to Lingui internal format. 
I removed this code duplication by exporting from `@lingui/core` a `parseMessage` function and reusing it in all subpackages. 

2. I simplified the way how the compiled catalogs produced. This was for 3 purposes: 
   1. to reuse mentioned function
   2. to make code much cleaner and smaller
   3. to make reading of catalogs actually faster than before. 

Before compiled catalogs were produced as js template literal (js code) and complicated AST manipulation was involved
```js
export const messages = {
  messageId: "message value"
}
```
Now i'm just using JSON.stringify / JSON.parse
```js
export const messages = JSON.parse("{
 "messageId": "message value"
}")
```
Why it's better you can read here https://v8.dev/blog/cost-of-javascript-2019#json

2023-01-10 18:51 UTC, Martin005 requested changes
Thank you for the changes, I think that all of what you mentioned makes perfect sense including the JSON.stringify/JSON.parse! 🙂

When I tried your branch as a local package, I immediately noticed one mistake, so **please have a look at my comments and resolve them**.

When I resolved the mistake locally, I also tried all 4 issues #1033, #1075, #1278 and #1303 and I can confirm that all of them are fixed with this new version of `@messageformat/parser` package 🥳

2023-01-10 18:51 UTC, Martin005 commented on packages/core/src/i18n.ts
> +  plurals?: (n: number, ordinal?: boolean) => number
The return type needs to be `PluralCategory` from the `make-plural` instead of `number`.

2023-01-11 08:18 UTC, thekip commented
Fixed

2023-01-11 08:31 UTC, thekip commented
I also thinking on how to hide exposed but treated as internal APIs, for example that `formatMessage` is supposed to be internal api, but because we use it in other packages it should be exported. 

There should be either special naming convention, or may be just JSdoc would be enough

2023-01-11 08:32 UTC, thekip commented
I see tests are failing, i will have a look

2023-01-11 08:50 UTC, thekip commented
I've ported some changes from this PR https://github.com/lingui/js-lingui/pull/1328

> I deleted pure option from createCompiledCatalog because it's not used anywhere in the project. This API considered internal, so we should be on the safe side.
It's probably was created for remote-loader but code has been changed since then and now this option is obsolete.

And also i've ported tests, because previous ones didn't test anything (there was a logical issue)

2023-01-11 11:36 UTC, Martin005 approved these changes
Great, thank you for the changes!

2023-01-11 12:14 UTC, merged