Refactor/build
lingui/js-lingui pull request #1336
Opened 2023-01-12 13:30 UTC by thekip

Fix size-limit issue 
And fix bundle sizr issue introduced by @message-format/parser exported from @lingui/core

Refactor and rewrite to typescript build scripts

2023-01-12 13:52 UTC, thekip commented
Still failing, that strange

2023-01-12 14:02 UTC, thekip commented
It worked with flat exports, and started failing again because of multi-entry, probable i've created inner entry incorrectly

2023-01-12 14:48 UTC, thekip commented
🎉 builds!  Size testing failing because it's trying to compare with master and master has a failing code now.

2023-01-12 17:59 UTC, Martin005 commented
@thekip
I have encountered several issues with your implementation:

1. After I built the library and released it locally with the `/scripts/verdaccio-release.js` script, I tried installing it in the current example `create-react-app` and running with `yarn start`, but I got the following error:
```
node:internal/modules/cjs/loader:535
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/martin/js-lingui/examples/create-react-app/node_modules/@lingui/conf/package.json
```

2. Following the [CONTRIBUTING.md](https://github.com/lingui/js-lingui/blob/main/CONTRIBUTING.md#contributing-the-code):

- When I run `release:test`, I get the following error:
```
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '/home/martin/js-lingui/scripts/build'
```

- Also, when I run `tsc` (as a part of the `lint:all` command in the main `package.json`), I get the following error:

```
$ /home/martin/js-lingui/node_modules/.bin/tsc
packages/core/build/cjs/dev/index.d.ts:1:10 - error TS2305: Module '"../compile/compileMessage"' has no exported member 'compileMessage'.

1 import { compileMessage as compile } from "../compile/compileMessage";
           ~~~~~~~~~~~~~~

packages/core/build/esm/dev/index.d.ts:1:10 - error TS2305: Module '"../compile/compileMessage"' has no exported member 'compileMessage'.

1 import { compileMessage as compile } from "../compile/compileMessage";
           ~~~~~~~~~~~~~~
```

2023-01-12 18:09 UTC, andrii-bodnar commented
We'd like to have a separate fix for the bug in `main` and separately the rest (just to not block the new version release)

2023-01-13 07:39 UTC, thekip commented
> We'd like to have a separate fix for the bug in main and separately the rest (just to not block the new version release)
it's not possible to ship it separately, to fix the `main` building system should be changed.
You can disable or ignore size-limit issue for now and ship without it, code should work, it's just an issue with workflow in the monorepo. 

> Also, when I run tsc (as a part of the lint:all command in the main package.json), I get the following error:
Why it's not failing in CI?

2023-01-13 07:43 UTC, andrii-bodnar commented
@thekip what exactly went wrong in the #1328 that broke this size-check? It might be easier to rollback this change than dangerously change the build system.

It worked before and it's not a good idea to ignore this.

2023-01-13 07:48 UTC, thekip commented
> so in short
this is a first time usage of the cross-linked library in client-side code
There are also lingui/react which states that uses core package, but actually it uses only typings, so in real js code imports to core are stripped
and currently when webpack starts resolving imports it goes to ./packages/core/ instead of ./package/core/dst because this is how yarn workspace linking works
When we deploy packages, it deployed from ./dst
but when thy used locally, they used from ./ {root of package}
it means  the changes should be bigger to support this
i will try to find a quick workaround for that

2023-01-13 07:50 UTC, thekip commented
In my opinion it's better to "dangerously" change the build system (which in fact is not dangerously)

2023-01-13 08:35 UTC, thekip commented
`release:test` and `lint:all` are fixed. 

Actually `release:test` are useless today, it's doing the same thing as in CI but with diffrent code. So issue was in file itself not in tests. 

Typings was failing because i marked `compileMessage` as `@internal`, and typescript stripped the typings of it. (that's exactly what i wanted to achieve). 

I deleted /dev folder with all content and reorganized it in different way. Probably previously (prior v3)  the `dev` was somehow exposed from the package, but right now in current `main` code it's no longer exposed, and users have no chance to use anything from there, so it's safe. 


Looking into issue with No "exports" with @lingui/conf

2023-01-13 09:18 UTC, thekip commented
Fixed all issues, now it works in examples. But came up with better (less fragile) idea, i will try to implement it and look what i get

2023-01-13 11:20 UTC, thekip commented
@Martin005 @andrii-bodnar was managed to simplify process and remove fragile parts. If you're afraid of changes, we can discuss how the process previously looks like, and how it's looks now. 

In short: 

We do not copy package.json from root of package to ./build, instead we publish package  from the package root. This is how it's done in most of the projects on the market. This simplifies things a lot and fix issues with size-check among with others.

2023-01-16 09:44 UTC, Martin005 requested changes

2023-01-16 09:44 UTC, Martin005 commented on scripts/build/packaging.ts
> +  const _filename = filename.replace(/^@lingui\//, "")
Isn't this replace now outdated as you have removed the `@lingui` prefix from all package names in the `bundles.ts` file?

2023-01-16 09:44 UTC, Martin005 commented on scripts/build/packaging.ts
> +import {existsSync, readdirSync, unlinkSync} from "fs"
`unlinkSync` is now not used and can be removed

2023-01-16 09:44 UTC, Martin005 commented on scripts/build/utils.ts
> +  return new Promise((resolve, reject) => {
```suggestion
  return new Promise<void>((resolve, reject) => {
```

2023-01-16 09:44 UTC, Martin005 commented on scripts/build/utils.ts
> +  return new Promise((resolve, reject) =>
```suggestion
  return new Promise<void>((resolve, reject) =>
```

2023-01-16 09:44 UTC, Martin005 commented on scripts/build/rollup.ts
> +
This empty line can be removed

2023-01-16 13:14 UTC, Martin005 approved these changes

2023-01-16 13:34 UTC, andrii-bodnar approved these changes

2023-01-16 13:35 UTC, merged