docs(): various refinements
lingui/js-lingui pull request #1370
Opened 2023-01-25 13:18 UTC by andrii-bodnar

2023-01-25 13:55 UTC, Martin005 requested changes
There are still a few places in the code that point to `lingui.js.org`. Could you please update them as well? 🙂

2023-01-25 13:55 UTC, Martin005 commented on packages/cli/src/lingui-extract.ts
> +      " Please set extractBabelOptions in configuration https://lingui.dev/ref/conf#extractBabelOptions"
This anchor doesn't work as anchors are case sensitive. Please update `#extractBabelOptions` to be in lower-case

2023-01-25 13:55 UTC, Martin005 commented on packages/core/README.md
> +[tutorial]: https://lingui.dev/tutorials/js
This was moved to `https://lingui.dev/tutorials/javascript`

2023-01-25 15:33 UTC, andrii-bodnar commented
There are still a few `lingui.js.org` links in the `CHANGELOG.md` files, I think it will be better not to touch these files and keep this history as is.

2023-01-26 08:25 UTC, Martin005 approved these changes

2023-01-26 08:33 UTC, merged