fix: Named components not working in Trans in @lingui/react
lingui/js-lingui pull request #1402
Opened 2023-02-03 18:44 UTC by Martin005

# Description
This PR fixes #1400 by allowing the tag names to be not only digits, but letters as well.
For more information, please visit the original issue #1400.

## Types of changes

[//]: # (What types of changes does your code introduce to Lingui?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/lingui/js-lingui/blob/main/CONTRIBUTING.md) and [CODE_OF_CONDUCT](https://github.com/lingui/js-lingui/blob/main/CODE_OF_CONDUCT.md) docs
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

2023-02-03 19:12 UTC, thekip requested changes

2023-02-03 19:12 UTC, thekip commented on packages/react/src/Trans.test.tsx
> +  })
I would also add a test with multiple components nested in each other:

```jsx
<Trans
        id="Read <link>the <strong>docs</strong></link>"
        components={{ link: <a href="/docs" />, strong: <strong /> }}
      />
```

2023-02-06 08:10 UTC, andrii-bodnar approved these changes

2023-02-06 08:10 UTC, andrii-bodnar commented
@Martin005 thank you!

2023-02-06 08:19 UTC, thekip approved these changes

2023-02-06 08:21 UTC, merged