Merge pull request #1399 from lingui/main
lingui/js-lingui pull request #1431
Opened 2023-02-12 11:29 UTC by Martin005

# Description
Based on suggestion from #1186, this PR adds flattening of ICU messages for the `extract` and `extract-template` CLI commands.

Fixes #1186

## Types of changes

[//]: # (What types of changes does your code introduce to Lingui?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [X] I have read the [CONTRIBUTING](https://github.com/lingui/js-lingui/blob/main/CONTRIBUTING.md) and [CODE_OF_CONDUCT](https://github.com/lingui/js-lingui/blob/main/CODE_OF_CONDUCT.md) docs
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

2023-02-13 08:08 UTC, andrii-bodnar approved these changes

2023-02-13 08:18 UTC, thekip requested changes
How this supposed to work in general? When the message would be flattened, it would be a different string. And it would not match to id string from runtime.

2023-02-13 08:47 UTC, thekip commented on packages/core/src/flatten/flattenMessage.ts
> +      return [cloned]
Without `reduce`, mutating data and `cloneDeep`: 

```ts
return [{
  ...token,
  cases: token.cases.map((k, index) => {
    const newValue = flattenTokens([
      ...tokens.slice(0, i),
      ...cases[index].tokens,
      ...tokens.slice(i + 1)
    ])

    return {...k, tokens: newValue}
  })
}]
```

2023-02-13 15:24 UTC, thekip commented
@Martin005 

> How this supposed to work in general? When the message would be flattened, it would be a different string. And it would not match to id string from runtime.

I see here a couple ways how this could be done: 

1. This logic should be applied in the macro and not in extractor. This way macro will generate flatten messages, left them in the bundle where extractor would pick them up. But we should consider SWC version of macro, and porting these changes to the SWC would be hard (because it depends on `@message-parser`). So i would not recommend this option. 

2. Implement it together with hash based id proposal. This way a hash would be generated by macro from the original, untouched message. And extractor with `--flat` would process only "messages" not ids. The only one problem here - this will not work for users who not used macro and not use explicit ids.  Actually, for v4 we can force explicit ids to be used for non-macro usage.

2023-02-14 13:53 UTC, Martin005 commented
@thekip I have been thinking and I believe that the second option would be the best way to go.

2023-02-14 14:07 UTC, thekip commented
Yes, this is exactly how i'm see implementation of hash-based ids with macro. 

Two cases: 

1. Without macro, `i18n._()` call, id is required. Message would not be used as substitution.
2. Macro `t` calls will generate hash based ids from message if explicit ids is not specified, and this behavior would be enabled as default.

2023-03-01 08:43 UTC, closed without merging